apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  project: default
  source:
    repoURL: "https://github.com/hassan308/iac-helm.git"
    path: myapp-helm-charts/myapp
    targetRevision: HEAD
    helm:
      valueFiles:
        - "values-dev.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
