apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  project: default
  source:
    repoURL: 'https://github.com/hassan308/iac-helm.git'
    path: myapp-helm-charts/myapp
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml        # Standard värdefil som alltid finns i en Helm-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
